version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 244254618249.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=244254618249.dkr.ecr.us-east-1.amazonaws.com/lab-pipeline-ecs
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - pwd
      - ls
      - cd app01
      - ls
      - pwd
      - cat Dockerfile
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker --version
      - sudo docker ps
      - sudo docker build -t $REPOSITORY_URI:latest .
      - sudo docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"lab-pipeline-ecs","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
      - pwd
      - ls
artifacts:
    files:
      - app01/imagedefinitions.json
